sudo: required
services:
  - docker
language: python

addons:
  apt:
    sources:
    - debian-sid    # Grab shellcheck from the Debian repo (o_O)
    packages:
    - shellcheck

env:
  - IGNORE_DOCKER_VERSION=true PYTHONUNBUFFERED=true

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - pip install pip --upgrade
  - pip install git+https://github.com/timothyb89/dbuild.git
  - pip install google-cloud-storage
  - pip install flake8 flake8-blind-except flake8-builtins flake8-pep3101 flake8-coding
  - pip install pylint
  - docker --version
  - docker-compose --version

jobs:
  include:
    - stage: lint-shellcheck
      script: bash -c 'shopt -s globstar; shellcheck **/*.sh'
    - stage: linting-flake8
      script: flake8
    - stage: linting-pylint
      script: pylint
    - stage: lint-shellcheck
      script: bash -c 'shopt -s globstar; shellcheck **/*.sh'
    - stage: metrics-pipeline
      script: python ci.py metrics
    - stage: logs-pipeline
      script: python ci.py logs False
