sudo: required
services:
  - docker
language: python

env:
  - IGNORE_DOCKER_VERSION=true

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - pip install pip --upgrade
  - pip install git+https://github.com/timothyb89/dbuild.git
  - pip install google-cloud-storage
  - docker --version
  - docker-compose --version

jobs:
  include:
    - stage: metrics-pipeline
      script: travis_wait python ci.py metrics
    - stage: logs-pipeline
      script: python ci.py logs False
