version: '3'
services:

  memcached:
    image: memcached:${MEMCACHED_VERSION:-1.5.0-alpine}

  influxdb:
    image: influxdb:${INFLUXDB_VERSION:-1.3.2-alpine}
  influxdb-init:
    image: monasca/influxdb-init:${INFLUXDB_INIT_VERSION:-latest}
    depends_on:
      - influxdb

  # cadvisor will allow host metrics to be collected, but requires significant
  # access to the host system
  # if this is not desired, the following can be commented out, and the CADVISOR
  # environment variable should be set to "false" in the `agent-collector`
  # block - however no metrics will be collected
  cadvisor:
    image: google/cadvisor:${CADVISOR_VERSION:-v0.26.1}
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker:/var/lib/docker:ro"

  agent-forwarder:
    image: monasca/agent-forwarder:${MON_AGENT_FORWARDER_VERSION:-master}
    environment:
      NON_LOCAL_TRAFFIC: "true"

  agent-collector:
    image: monasca/agent-collector:${MON_AGENT_COLLECTOR_VERSION:-master}
    environment:
      AGENT_HOSTNAME: "docker-host"
      FORWARDER_URL: "http://agent-forwarder:17123"
      CADVISOR: "true"
      CADVISOR_URL: "http://cadvisor:8080/"

  alarms:
    image: monasca/alarms:${MON_ALARMS_VERSION:-1.1.0}

  zookeeper:
    image: zookeeper:${ZOOKEEPER_VERSION:-3.4}
  kafka:
    image: monasca/kafka:${MON_KAFKA_VERSION:-0.9.0.1-2.11-1.0.2}
    depends_on:
      - zookeeper
  kafka-init:
    image: monasca/kafka-init:${MON_KAFKA_INIT_VERSION:-0.0.1}
    environment:
      ZOOKEEPER_CONNECTION_STRING: "zookeeper:2181"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_TOPIC_CONFIG: segment.ms=900000 # 15m
      KAFKA_CREATE_TOPICS: "\
        metrics:64:1,\
        alarm-state-transitions:12:1,\
        alarm-notifications:12:1,\
        retry-notifications:3:1,\
        events:12:1,\
        60-seconds-notifications:3:1"
    depends_on:
      - zookeeper

  mysql:
    image: mysql:${MYSQL_VERSION:-5.5}
    environment:
      MYSQL_ROOT_PASSWORD: secretmysql
  mysql-init:
    image: monasca/mysql-init:${MYSQL_INIT_VERSION:-1.5.1}
    environment:
      MYSQL_INIT_DISABLE_REMOTE_ROOT: "false"
      MYSQL_INIT_RANDOM_PASSWORD: "false"

  keystone:
    image: monasca/keystone:1.1.1
    environment:
      KEYSTONE_HOST: keystone
      KEYSTONE_PASSWORD: secretadmin
      KEYSTONE_DATABASE_BACKEND: mysql
      KEYSTONE_MYSQL_HOST: mysql
      KEYSTONE_MYSQL_USER: keystone
      KEYSTONE_MYSQL_PASSWORD: keystone
      KEYSTONE_MYSQL_DATABASE: keystone
    depends_on:
      - mysql
    ports:
      - "5000:5000"
      - "35357:35357"

  monasca-sidecar:
    image: timothyb89/monasca-sidecar:1.0.0

  monasca:
    image: monasca/api:master
    environment:
      SIDECAR_URL: http://monasca-sidecar:4888/v1/ingest
    depends_on:
      - influxdb
      - keystone
      - mysql
      - zookeeper
      - kafka
      - monasca-sidecar
      - memcached
    ports:
      - "8070:8070"

  monasca-persister:
    image: monasca/persister:master
    depends_on:
      - monasca
      - influxdb
      - zookeeper
      - kafka

  thresh:
    image: monasca/thresh:latest
    environment:
      NO_STORM_CLUSTER: "true"
      WORKER_MAX_HEAP_MB: "256"
    depends_on:
      - zookeeper
      - kafka

  monasca-notification:
    image: monasca/notification:master
    environment:
      NF_PLUGINS: "webhook"
    depends_on:
      - monasca
      - zookeeper
      - kafka
      - mysql

  grafana:
    image: monasca/grafana:4.0.0-1.1.1
    environment:
      GF_AUTH_BASIC_ENABLED: "false"
      GF_USERS_ALLOW_SIGN_UP: "true"
      GF_USERS_ALLOW_ORG_CREATE: "true"
      GF_AUTH_KEYSTONE_ENABLED: "true"
      GF_AUTH_KEYSTONE_AUTH_URL: http://keystone:5000
      GF_AUTH_KEYSTONE_VERIFY_SSL_CERT: "false"
      GF_AUTH_KEYSTONE_DEFAULT_DOMAIN: "Default"
    ports:
      - "3000:3000"
    depends_on:
      - keystone
      - monasca

  grafana-init:
    image: monasca/grafana-init:1.1.0
    depends_on:
      - grafana
