version: '2'
services:
  influxdb:
    image: influxdb:latest
  influxdb-init:
    image: monasca/influxdb-init:latest
    depends_on:
      - influxdb

  zookeeper:
    image: zookeeper:3.3
  kafka:
    image: monasca/kafka:0.9.0.1-2.11
    environment:
      ZOOKEEPER_CONNECTION_STRING: "zookeeper:2181"
      KAFKA_AUTO_CREATE_TOPICS: "false"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_CREATE_TOPICS: "\
        metrics:64:1,alarm-state-transitions:16:1,\
        alarm-notifications:16:1,retry-notifications:16:1,\
        events:16:1"
    depends_on:
      - zookeeper

  mysql:
    image: mysql:5.5
    environment:
      MYSQL_ROOT_PASSWORD: secretmysql
  mysql-init:
    image: monasca/mysql-init:1.0.0
    environment:
      MYSQL_INIT_DISABLE_REMOTE_ROOT: "true"
      MYSQL_INIT_RANDOM_PASSWORD: "true"

  keystone:
    image: monasca/keystone:1.0.6
    environment:
      KEYSTONE_HOST: keystone
      KEYSTONE_PASSWORD: secretadmin
      KEYSTONE_DATABASE_BACKEND: mysql
      KEYSTONE_MYSQL_HOST: mysql
      KEYSTONE_MYSQL_USER: keystone
      KEYSTONE_MYSQL_PASSWORD: keystone
      KEYSTONE_MYSQL_DATABASE: keystone
    volumes:
      - ./keystone/preload.yml:/preload.yml
    depends_on:
      - mysql
    ports:
      - "5000:5000"
      - "35357:35357"

  monasca-sidecar:
    image: timothyb89/monasca-sidecar:1.0.0

  monasca:
    image: monasca/api:master-prometheus
    environment:
      SIDECAR_URL: http://monasca-sidecar:4888/v1/ingest
    depends_on:
      - influxdb
      - keystone
      - mysql
      - zookeeper
      - kafka
      - monasca-sidecar
    ports:
      - "8070:8070"

  monasca-persister:
    image: monasca/persister:master
    command: sh -c "sleep 15 && /start.sh"
    depends_on:
      - monasca
      - influxdb
      - zookeeper
      - kafka

  grafana:
    image: monasca/grafana:4.1.0-pre1-1.0.0
    environment:
      GF_AUTH_BASIC_ENABLED: "false"
      GF_USERS_ALLOW_SIGN_UP: "true"
      GF_USERS_ALLOW_ORG_CREATE: "true"
      GF_AUTH_KEYSTONE_ENABLED: "true"
      GF_AUTH_KEYSTONE_AUTH_URL: http://keystone:5000
      GF_AUTH_KEYSTONE_VERIFY_SSL_CERT: "false"
      GF_AUTH_KEYSTONE_DEFAULT_DOMAIN: "Default"
    ports:
      - "3000:3000"
    depends_on:
      - keystone
      - monasca

  grafana-init:
    image: monasca/grafana-init:1.0.0
    depends_on:
      - grafana
